Dashboard/urls.py
from django.urls import path, include
from Dashboard import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import ChangePasswordForm

app_name = 'Dashboard'

urlpatterns = [
    path('', views.ContactView.as_view(), name='home'),
    # Urls del sistema de autenticación de usuarios
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name="Dashboard/password_change.html",
        form_class=ChangePasswordForm,
        success_url=reverse_lazy("Dashboard:password_change_done")),name="password_change"),

    path('change-password-done/', auth_views.PasswordChangeView.as_view(
        template_name="Dashboard/password_change_done.html"),
        name="password_change_done"),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="Dashboard/password_reset_form.html",
        email_template_name="Dashboard/password_reset_email.html",
        subject_template_name="Dashboard/password_reset_subject.txt",
        success_url = reverse_lazy("Dashboard:password_reset_done")),
        name="password_reset"),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name="Dashboard/password_reset_done.html"),
        name="password_reset_done"),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="Dashboard/password_reset_confirm.html",
        success_url = reverse_lazy("Dashboard:password_reset_complete")),
        name="password_reset_confirm"),

    path('reset_done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="Dashboard/password_reset_complete.html"),
        name="password_reset_complete"),

    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.NewUser.as_view(), name="new_user"),
    # Urls del panel de control
    path('panel/', views.Panel.as_view(), name="panel"),
    # Urls de restaurant
    path('panel/new_restaurant/',views.CreateRestaurant.as_view(), name="new_restaurant"),
    path('panel/update_restaurant/<int:pk>',views.UpdateRestaurant.as_view(), name="update_restaurant"),
    path('panel/delete/<int:pk>/',views.DeleteRestaurant.as_view(), name="delete_restaurant"),
    path('panel/list_restaurant/', views.ListRestaurant.as_view(), name="list_restaurant"),
    path('panel/restaurant_detail/<int:pk>', views.Detail.as_view(), name="restaurant_detail"),

    # Urls de dish
    path('panel/create_dish/<int:restaurant>', views.CreateDish.as_view(), name="create_dish"),
    path('panel/list_dish/<int:restaurant>/', views.ListDish.as_view(), name="list_dish"),
    path('panel/update_dish/<int:pk>', views.UpdateDish.as_view(), name="update_dish"),
    path('panel/delete_dish/<int:pk>', views.DeleteDish.as_view(), name="delete_dish"),
    # Urls de client
    path('panel/update_profile/<int:pk>', views.UpdateProfile.as_view(), name="update_profile"),
    path('panel/update_plan/', views.UpdatePlan.as_view(), name="update_plan"),
    # Urls de Shedules
    path('panel/create_shedule/<int:pk>', views.CreateShedule.as_view(), name="create_shedule"),
    path('panel/list_shedule/<int:pk>', views.ListShedule.as_view(), name="list_shedule"),
    path('panel/update_shedule/<int:pk>', views.UpdateShedule.as_view(), name="update_shedule"),
    path('panel/delete_shedule/<int:pk>', views.DeleteShedule.as_view(), name="delete_shedule"),
    # Urls de Media
    path('panel/create_social/<int:pk>', views.CreateSocial.as_view(), name="create_social"),
    path('panel/create_media/<int:pk>', views.CreateMedia.as_view(), name="create_media"),
    path('panel/list_media/<int:pk>', views.ListMedia.as_view(), name="list_media"),
    path('panel/update_social/<int:pk>', views.UpdateSocial.as_view(), name="update_social"),
]

flavors/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dashboard.urls')),
]

Dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Timestamp model to save the date of every transaction of the rest of the models
class Timestamp(models.Model):
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)
    update_at = models.DateField(auto_now=True)
    delete_at = models.DateField(auto_now=True)

    class Meta:
        abstract = True


# Client model that will be used to register new clients in the system
class Client(models.Model):
    PLAN_CHOICES = [
        ('S', 'Sencillo'),
        ('P', 'Premium'),
        ('I', 'Ilimitado'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, null=True, blank=True)
    plan = models.CharField(max_length=1, choices=PLAN_CHOICES, default='S')
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

# Restaurant model to every restaurant saved in the system.


class Restaurant(Timestamp):
    name = models.CharField(max_length=50)
    address = models.TextField()
    logo_url = models.URLField(max_length=200)
    web_site = models.URLField(max_length=200)
    status = models.BooleanField('open', blank=False, null=False, default=True)
    active = models.BooleanField('active', blank=False, null=False, default=True)
    owner = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(Timestamp):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Flavor(Timestamp):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Dish(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    flavors = models.ManyToManyField(Flavor)

    def __str__(self):
        return self.name


class Day(models.Model):
    DAYS_OF_WEEK = (
        ('D', 'Sunday'),
        ('L', 'Monday'),
        ('M', 'Tuesday'),
        ('MI', 'Wednesday'),
        ('J', 'Thursday'),
        ('V', 'Friday'),
        ('S', 'Saturday'),
    )
    day = models.CharField(max_length=2, choices=DAYS_OF_WEEK, default='D')

    def __str__(self):
        return self.day


class Shedule(models.Model):
    days = models.ManyToManyField(Day)
    time_open = models.TimeField()
    time_close = models.TimeField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    active = models.BooleanField('active', blank=False, null=False, default=True)

    def __str__(self):
        return self.restaurant.name


class Social(Timestamp):

    name = models.CharField(max_length=14, unique=True)

    def __str__(self):
        return self.name


class Media(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    social = models.ForeignKey(Social, on_delete=models.CASCADE)
    red = models.URLField(max_length=200, unique=True, blank=False, null=False, default='www.google.com')
    active = models.BooleanField('active', blank=False, null=False, default=True)

    def __str__(self):
        return self.social.name

Dashboard/views.py
from itertools import chain

import pytz
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, reverse, render_to_response
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.http.response import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import *
from django.views.generic import CreateView, FormView, UpdateView, TemplateView, ListView, DeleteView
from .models import Client, Restaurant, Dish, Category, Flavor, Shedule, Media, Social

# Create your views here.

''' 
------------------------------------------
Views sistema de autenticación de usuarios
------------------------------------------
'''


class NewUser(CreateView):
    model = User
    template_name = 'Dashboard/new-user-form.html'
    form_class = UserForm
    success_url = '/'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_cliente = ClientFormSet()
        return self.render_to_response(self.get_context_data(form=form, detalle_client_form_set=detalle_cliente))

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        client_form_set = ClientFormSet(request.POST)
        if form.is_valid() and client_form_set.is_valid():

            return self.form_valid(form, client_form_set)
        else:
            return self.form_invalid(form, client_form_set)

    def form_valid(self, form, client_form_set):
        self.object = form.save()
        self.object.set_password(form.cleaned_data['password'])
        self.object.save()
        self.object = authenticate(
            username=self.object.username, password=form.cleaned_data['password'])
        client_form_set.instance = self.object
        client_form_set.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, client_form_set):
        return self.render_to_response(self.get_context_data(form=form, detalle_client_form_set=client_form_set))


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'Dashboard/login.html'
    success_url = reverse_lazy("Dashboard:panel")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            login(self.request, form.get_user())
            return super(LoginView, self).form_valid(form)
        else:
            return super(LoginView, self).form_invalid(form)


def logout_view(request):
    logout(request)
    return render(request, 'Dashboard/index.html')


''' 
------------------------------------------
Views landing page
------------------------------------------
'''


class Home(TemplateView):
    template_name = "Dashboard/index.html"


class ContactView(FormView):
    template_name = 'Dashboard/index.html'
    form_class = ContactForm
    success_url = '/'

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


''' 
------------------------------------------
Views panel de control
------------------------------------------
'''


class Panel(LoginRequiredMixin, TemplateView):
    template_name = "Panel/index.html"
    login_url = 'Dashboard:login'


class CreateRestaurant(LoginRequiredMixin, CreateView):
    form_class = RestaurantForm
    template_name = "Restaurants/new_restaurant.html"
    success_url = reverse_lazy("Dashboard:list_restaurant")

    login_url = 'Dashboard:login'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            restaurant = form.save(commit=False)
            restaurant.owner = self.get_object()
            restaurant.save()
            return super(CreateRestaurant, self).form_valid(form)
        else:
            return super(CreateRestaurant, self).form_invalid(form)

    def get_object(self):
        client = Client.objects.get(user=self.request.user)
        return client


class UpdateRestaurant(LoginRequiredMixin, UpdateView):
    model = Restaurant
    form_class = RestaurantForm
    template_name = "Restaurants/update_restaurant.html"
    success_url = reverse_lazy("Dashboard:list_restaurant")
    login_url = 'Dashboard:login'

    def get_queryset(self):
        self.queryset = Restaurant.objects.filter(id=self.kwargs['pk'], owner=self.request.user.client, active=True)
        get_object_or_404(self.queryset, id=self.kwargs['pk'], owner=self.request.user.client, active=True)
        return self.queryset


class ListRestaurant(LoginRequiredMixin, ListView):
    model = Restaurant
    template_name = "Panel/list_restaurant.html"
    login_url = 'Dashboard:login'

    def get_queryset(self):
        queryset = Restaurant.objects.filter(
            owner=self.request.user.client, active=True)
        return queryset


class Detail(LoginRequiredMixin, TemplateView):
    model = Restaurant
    template_name = "Panel/restaurant_detail.html"
    login_url = 'Dashboard:login'

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class CreateDish(LoginRequiredMixin, CreateView):
    model = Dish
    form_class = DishForm
    template_name = "Panel/create_dish.html"
    success_url = reverse_lazy("Dashboard:list_restaurant")

    def get_form(self, *args, **kwargs):
        form = super(CreateDish, self).get_form(*args, **kwargs)
        form.fields['restaurant'].queryset = Restaurant.objects.filter(id=self.kwargs['restaurant'])
        return form

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})


class ListDish(LoginRequiredMixin, ListView):
    model = Dish
    template_name = "Panel/list_dish.html"
    form_class = DishForm

    def get_queryset(self):
        self.queryset = super(ListDish, self).get_queryset().filter(restaurant_id=self.kwargs['restaurant'])
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(ListDish, self).get_context_data(**kwargs)
        context['restaurant'] = self.kwargs['restaurant']
        return context


class UpdateDish(LoginRequiredMixin, UpdateView):
    model = Dish
    form_class = DishForm
    template_name = 'Panel/update_dish.html'
    success_url = reverse_lazy("Dashboard:list_restaurant")
    login_url = 'Dashboard:login'

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})

    def get_queryset(self):
        self.queryset = super(UpdateDish, self).get_queryset().filter(id=self.kwargs['pk'],
                                                                      restaurant__owner_id=self.request.user.client.id)
        get_object_or_404(self.queryset, id=self.kwargs['pk'], restaurant__owner_id=self.request.user.client.id)
        return self.queryset


class DeleteDish(LoginRequiredMixin, DeleteView):
    model = Dish
    template_name = 'Panel/delete_dish.html'
    success_url = reverse_lazy("Dashboard:list_restaurant")
    login_url = 'Dashboard:login'

    def get_queryset(self):
        dish = self.kwargs['pk']
        return self.model.objects.filter(id=dish)

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})


class CreateShedule(LoginRequiredMixin, CreateView):
    model = Shedule
    form_class = SheduleForm
    template_name = 'Panel/create_shedule.html'

    def get_form(self, *args, **kwargs):
        form = super(CreateShedule, self).get_form(*args, **kwargs)
        form.fields['restaurant'].queryset = Restaurant.objects.filter(id=self.kwargs['pk'], owner_id=self.request.user.client.id)
        return form

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})


class ListShedule(LoginRequiredMixin, ListView):
    model = Shedule
    template_name = 'Panel/list_shedule.html'

    def get_queryset(self):
        self.queryset = Shedule.objects.filter(active=True, restaurant__id=self.kwargs['pk'], restaurant__owner_id=self.request.user.client.id)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(ListShedule, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class UpdateShedule(LoginRequiredMixin, UpdateView):
    model = Shedule
    template_name = 'Panel/update_shedule.html'
    form_class = SheduleForm

    def get_queryset(self):
        self.queryset = super(UpdateShedule, self).get_queryset().filter(active=True,
                                                                         restaurant__owner_id=self.request.user.client.id)
        get_object_or_404(self.queryset, id=self.kwargs['pk'], active=True,
                          restaurant__owner_id=self.request.user.client.id)
        return self.queryset

    def get_success_url(self):
        pk = self.kwargs['pk']

Dashboard/templates/Panel/create_dish.html
{% extends "Panel/base.html" %}

{% block titulo %}
  Restaurantes
{% endblock titulo %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

Dashboard/templates/Panel/delete_dish.html
{% extends "Panel/base.html" %}

{% block titulo %}
  Eliminar {{ dish.name }}
{% endblock titulo %}

{% block content %}
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <div class="row d-flex">
                <div class="col-lg-12">
                    <div class="p-5">
                        <form method="POST" class="user">
                            {% csrf_token %}
                            <h3>¿ Está seguro de eliminar {{ dish.name }} ?</h3>
                            <a class="btn btn-secondary mt-3 btn-sm" href="{% url 'Dashboard:list_restaurant'%}">Cancelar</a>
                            <button class="btn btn-danger mt-3 btn-sm" type="submit">Eliminar</button>
                          </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Dashboard/templates/Panel/list_dish.html
{% extends "Panel/base.html" %}

{% block titulo %}
  Platillos
{% endblock titulo %}
{% block content %}

 <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Lista de Platillos</h6>
    </div>
    <div class="card-body">
        {% if object_list %}

        <a class="btn btn-primary mb-3" href="{% url 'Dashboard:create_dish' restaurant %}">
            Agregar Platillo.
        </a>

        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Descripción</th>
                      <th>Precio</th>
                      <th>Restaurant</th>
                      <th>Categoria</th>
                      <th>Sabor</th>
                      <th>Opciones</th>
                    </tr>
                </thead>

                <tbody>
                    {% for restaurant in object_list %}
                    <tr>
                      <td>{{ restaurant.name }}</td>
                      <td>{{ restaurant.description }}</td>
                      <td>{{ restaurant.price }}</td>
                      <td>{{ restaurant.restaurant }}</td>
                      <td>
                        {% for categorie in restaurant.categories.all %}
                            {{ categorie }}
                            <br>
                        {% endfor %}
                      </td>
                        <td align="center">
                        {% for flavor in restaurant.flavors.all %}
                            {{ flavor }}
                        {% endfor %}
                        </td>
                      <td align="center">
                          <a href="{% url 'Dashboard:update_dish' restaurant.id %}"><i class="fas fa-pen-square"></i></a>
                          <a href="{% url 'Dashboard:delete_dish' restaurant.id %}"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        {% else  %}

        <h1 class="h4 text-gray-900 mb-4"> Aún no cuenta con Platillos </h1>
        <a class="btn btn-primary mb-3" href="{% url 'Dashboard:create_dish' restaurant%}">
            Nuevo Platillo.
        </a>

        {% endif %}

    </div>
 </div>

{% endblock content %}

Dashboard/templates/Panel/list_restaurant.html
{% extends "Panel/base.html" %}

{% block titulo %}
  Restaurantes
{% endblock titulo %}

{% block content %}

 <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Lista de Restaurantes</h6>
    </div>
    <div class="card-body">
        {% if object_list %}
        <a class="btn btn-primary mb-3" href="{% url 'Dashboard:new_restaurant' %}">
            Nuevo restaurante.
        </a>
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Dirección</th>
                      <!--<th>Logo</th>-->
                      <!--<th>Website</th>-->
                      <th>Opciones</th>
                      <th>Detalles</th>

                    </tr>
                </thead>
  
                <tbody>
                {% for object in object_list %}
                    <tr>
                      <td>{{ object.name }}</td>
                      <td>{{ object.address }}</td>
                      <!--<td><img src="{{ object.logo_url }}"></td>-->
                      <!--<td>{{ object.web_site }}</td>-->
                      <td align="center">
                          <a href="{% url 'Dashboard:update_restaurant' object.id %}"><i class="fas fa-pen-square"></i></a>
                          <a href="{% url 'Dashboard:delete_restaurant' object.id %}"><i class="fa fa-trash"></i></a>
                      </td>
                        <!--<td align="center">
                            <a href="{% url 'Dashboard:create_dish' object.id %}"><i class="fas fa-plus-square"></i></a>
                            <a href="{% url 'Dashboard:list_dish' object.id %}"><i class="fas fa-list"></i></a>
                        </td>-->
                        <td align="center">
                            <a href="{% url 'Dashboard:restaurant_detail' object.id %}"><i class="fas fa-plus-square"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        {% else  %}

        <h1 class="h4 text-gray-900 mb-4"> Aún no cuenta con Restaurantes </h1>
        <a class="btn btn-primary mb-3" href="{% url 'Dashboard:new_restaurant' %}">
            Nuevo restaurante.
        </a>
            
        {% endif %}

    </div>
 </div>
{% endblock content %}

Dashboard/templates/Panel/list_shedule.html
{% extends "Panel/base.html" %}

{% block titulo %}
  Horarios
{% endblock titulo %}
{% load static %}
{% block content %}
 <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Lista de Horarios</h6>
    </div>
    <div class="card-body">
        {% if object_list %}
        <a class="btn btn-primary mb-3" href="{% url 'Dashboard:create_shedule'  pk %}">
            Nuevo Horario.
        </a>
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      <th>Restaurante</th>
                      <th>Hora Apertura</th>
                      <th>Hora Cierre</th>
                      <th>Dias</th>
                      <th>Opciones</th>
                    </tr>
                </thead>

                <tbody>
                {% for object in object_list %}
                    <tr>
                      <td>{{ object.restaurant }}</td>
                      <td>{{ object.time_open }}</td>
                      <td>{{ object.time_close }}</td>
                      <td>
                          {% for day in object.days.all %}
                            {{ day }}
                          {% endfor %}

                      </td>
                      <td align="center">
                          <a href="{% url 'Dashboard:update_shedule' object.id %}"><i class="fas fa-pen-square"></i></a>
                          <a href="{% url 'Dashboard:delete_shedule' object.id %}"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        {% else  %}

        <h1 class="h4 text-gray-900 mb-4"> Aún no cuenta con Horarios </h1>
        <a class="btn btn-primary mb-3" href="{% url 'Dashboard:create_shedule' pk%}">
            Nuevo Horario.
        </a>

        {% endif %}

    </div>
 </div>

{% endblock content %}

Dashboard/templates/Panel/restaurant_detail.html
{% extends "Panel/base.html" %}

{% block titulo %}
  Restaurantes
{% endblock titulo %}

{% block content %}

 <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Lista de Detalles</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      <th>Platillos</th>
                      <th>Horarios</th>
                      <th>Redes Sociales</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td align="center">
                            <a href="{% url 'Dashboard:create_dish' pk  %}"><i class="fas fa-plus-square"></i></a>
                            <a href="{% url 'Dashboard:list_dish' pk %}"><i class="fas fa-list"></i></a>
                        </td>
                        <td align="center">
                            <a href="{% url 'Dashboard:create_shedule' pk  %}"><i class="fas fa-plus-square"></i></a>
                            <a href="{% url 'Dashboard:list_shedule' pk %}"><i class="fas fa-list"></i></a>
                        </td>
                        <td align="center">
                            <a href="{% url 'Dashboard:create_media' pk  %}"><i class="fas fa-plus-square"></i></a>
                            <a href="{% url 'Dashboard:list_media' pk %}"><i class="fas fa-list"></i></a>
                        </td>

                    </tr>
                </tbody>
            </table>
        </div>
    </div>
 </div>
{% endblock content %}

Dashboard/templates/Panel/update_dish.html
{% extends 'Panel/base.html' %}

{% block titulo %}
    Actualizar Platillo
{% endblock titulo %}


{% block content %}
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-5">
                            <div class="text-center">
                                <h1
                                    class="h4 text-gray-900 mb-4">
                                    <!-- Titulo del contenido -->
                                    Actualizar los datos del Platillo
                                </h1>
                            </div>
                            <form class="user" method="POST">
                                {% csrf_token %}

                                <div class="form-group">
                                    {{ form.as_p }}
                                </div>

                                <br/>
                                <hr/>
                                <br/>
                                <button class="btn btn-primary btn-user">
                                    Actualizar datos
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}