Dashboard/urls.py
from django.urls import path, include
from Dashboard import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import ChangePasswordForm

app_name = 'Dashboard'

urlpatterns = [
    path('', views.ContactView.as_view(), name='home'),
    # Urls del sistema de autenticación de usuarios
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name="Dashboard/password_change.html",
        form_class=ChangePasswordForm,
        success_url=reverse_lazy("Dashboard:password_change_done")),name="password_change"),

    path('change-password-done/', auth_views.PasswordChangeView.as_view(
        template_name="Dashboard/password_change_done.html"),
        name="password_change_done"),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="Dashboard/password_reset_form.html",
        email_template_name="Dashboard/password_reset_email.html",
        subject_template_name="Dashboard/password_reset_subject.txt",
        success_url = reverse_lazy("Dashboard:password_reset_done")),
        name="password_reset"),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name="Dashboard/password_reset_done.html"),
        name="password_reset_done"),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="Dashboard/password_reset_confirm.html",
        success_url = reverse_lazy("Dashboard:password_reset_complete")),
        name="password_reset_confirm"),

    path('reset_done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="Dashboard/password_reset_complete.html"),
        name="password_reset_complete"),

    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.NewUser.as_view(), name="new_user"),
    # Urls del panel de control
    path('panel/', views.Panel.as_view(), name="panel"),
    # Urls de restaurant
    path('panel/new_restaurant/',views.CreateRestaurant.as_view(), name="new_restaurant"),
    path('panel/update_restaurant/<int:pk>',views.UpdateRestaurant.as_view(), name="update_restaurant"),
    path('panel/delete/<int:pk>/',views.DeleteRestaurant.as_view(), name="delete_restaurant"),
    path('panel/list_restaurant/', views.ListRestaurant.as_view(), name="list_restaurant"),
    path('panel/restaurant_detail/<int:pk>', views.Detail.as_view(), name="restaurant_detail"),

    # Urls de dish
    path('panel/create_dish/<int:restaurant>', views.CreateDish.as_view(), name="create_dish"),
    path('panel/list_dish/<int:restaurant>/', views.ListDish.as_view(), name="list_dish"),
    path('panel/update_dish/<int:pk>', views.UpdateDish.as_view(), name="update_dish"),
    path('panel/delete_dish/<int:pk>', views.DeleteDish.as_view(), name="delete_dish"),
    # Urls de client
    path('panel/update_profile/<int:pk>', views.UpdateProfile.as_view(), name="update_profile"),
    path('panel/update_plan/', views.UpdatePlan.as_view(), name="update_plan"),
    # Urls de Shedules
    path('panel/create_shedule/<int:pk>', views.CreateShedule.as_view(), name="create_shedule"),
    path('panel/list_shedule/<int:pk>', views.ListShedule.as_view(), name="list_shedule"),
    path('panel/update_shedule/<int:pk>', views.UpdateShedule.as_view(), name="update_shedule"),
    path('panel/delete_shedule/<int:pk>', views.DeleteShedule.as_view(), name="delete_shedule"),
    # Urls de Media
    path('panel/create_social/<int:pk>', views.CreateSocial.as_view(), name="create_social"),
    path('panel/create_media/<int:pk>', views.CreateMedia.as_view(), name="create_media"),
    path('panel/list_media/<int:pk>', views.ListMedia.as_view(), name="list_media"),
    path('panel/update_social/<int:pk>', views.UpdateSocial.as_view(), name="update_social"),
]

flavors/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dashboard.urls')),
]

Dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Timestamp model to save the date of every transaction of the rest of the models
class Timestamp(models.Model):
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)
    update_at = models.DateField(auto_now=True)
    delete_at = models.DateField(auto_now=True)

    class Meta:
        abstract = True


# Client model that will be used to register new clients in the system
class Client(models.Model):
    PLAN_CHOICES = [
        ('S', 'Sencillo'),
        ('P', 'Premium'),
        ('I', 'Ilimitado'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, null=True, blank=True)
    plan = models.CharField(max_length=1, choices=PLAN_CHOICES, default='S')
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

# Restaurant model to every restaurant saved in the system.


class Restaurant(Timestamp):
    name = models.CharField(max_length=50)
    address = models.TextField()
    logo_url = models.URLField(max_length=200)
    web_site = models.URLField(max_length=200)
    status = models.BooleanField('open', blank=False, null=False, default=True)
    active = models.BooleanField('active', blank=False, null=False, default=True)
    owner = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(Timestamp):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Flavor(Timestamp):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Dish(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    flavors = models.ManyToManyField(Flavor)

    def __str__(self):
        return self.name


class Day(models.Model):
    DAYS_OF_WEEK = (
        ('D', 'Sunday'),
        ('L', 'Monday'),
        ('M', 'Tuesday'),
        ('MI', 'Wednesday'),
        ('J', 'Thursday'),
        ('V', 'Friday'),
        ('S', 'Saturday'),
    )
    day = models.CharField(max_length=2, choices=DAYS_OF_WEEK, default='D')

    def __str__(self):
        return self.day


class Shedule(models.Model):
    days = models.ManyToManyField(Day)
    time_open = models.TimeField()
    time_close = models.TimeField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    active = models.BooleanField('active', blank=False, null=False, default=True)

    def __str__(self):
        return self.restaurant.name


class Social(Timestamp):

    name = models.CharField(max_length=14, unique=True)

    def __str__(self):
        return self.name


class Media(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    social = models.ForeignKey(Social, on_delete=models.CASCADE)
    red = models.URLField(max_length=200, unique=True, blank=False, null=False, default='www.google.com')
    active = models.BooleanField('active', blank=False, null=False, default=True)

    def __str__(self):
        return self.social.name

Dashboard/views.py
from itertools import chain

import pytz
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, reverse, render_to_response
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.http.response import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import *
from django.views.generic import CreateView, FormView, UpdateView, TemplateView, ListView, DeleteView
from .models import Client, Restaurant, Dish, Category, Flavor, Shedule, Media, Social

# Create your views here.

''' 
------------------------------------------
Views sistema de autenticación de usuarios
------------------------------------------
'''


class NewUser(CreateView):
    model = User
    template_name = 'Dashboard/new-user-form.html'
    form_class = UserForm
    success_url = '/'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_cliente = ClientFormSet()
        return self.render_to_response(self.get_context_data(form=form, detalle_client_form_set=detalle_cliente))

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        client_form_set = ClientFormSet(request.POST)
        if form.is_valid() and client_form_set.is_valid():

            return self.form_valid(form, client_form_set)
        else:
            return self.form_invalid(form, client_form_set)

    def form_valid(self, form, client_form_set):
        self.object = form.save()
        self.object.set_password(form.cleaned_data['password'])
        self.object.save()
        self.object = authenticate(
            username=self.object.username, password=form.cleaned_data['password'])
        client_form_set.instance = self.object
        client_form_set.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, client_form_set):
        return self.render_to_response(self.get_context_data(form=form, detalle_client_form_set=client_form_set))


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'Dashboard/login.html'
    success_url = reverse_lazy("Dashboard:panel")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            login(self.request, form.get_user())
            return super(LoginView, self).form_valid(form)
        else:
            return super(LoginView, self).form_invalid(form)


def logout_view(request):
    logout(request)
    return render(request, 'Dashboard/index.html')


''' 
------------------------------------------
Views landing page
------------------------------------------
'''


class Home(TemplateView):
    template_name = "Dashboard/index.html"


class ContactView(FormView):
    template_name = 'Dashboard/index.html'
    form_class = ContactForm
    success_url = '/'

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


''' 
------------------------------------------
Views panel de control
------------------------------------------
'''


class Panel(LoginRequiredMixin, TemplateView):
    template_name = "Panel/index.html"
    login_url = 'Dashboard:login'


class CreateRestaurant(LoginRequiredMixin, CreateView):
    form_class = RestaurantForm
    template_name = "Restaurants/new_restaurant.html"
    success_url = reverse_lazy("Dashboard:list_restaurant")

    login_url = 'Dashboard:login'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            restaurant = form.save(commit=False)
            restaurant.owner = self.get_object()
            restaurant.save()
            return super(CreateRestaurant, self).form_valid(form)
        else:
            return super(CreateRestaurant, self).form_invalid(form)

    def get_object(self):
        client = Client.objects.get(user=self.request.user)
        return client


class UpdateRestaurant(LoginRequiredMixin, UpdateView):
    model = Restaurant
    form_class = RestaurantForm
    template_name = "Restaurants/update_restaurant.html"
    success_url = reverse_lazy("Dashboard:list_restaurant")
    login_url = 'Dashboard:login'

    def get_queryset(self):
        self.queryset = Restaurant.objects.filter(id=self.kwargs['pk'], owner=self.request.user.client, active=True)
        get_object_or_404(self.queryset, id=self.kwargs['pk'], owner=self.request.user.client, active=True)
        return self.queryset


class ListRestaurant(LoginRequiredMixin, ListView):
    model = Restaurant
    template_name = "Panel/list_restaurant.html"
    login_url = 'Dashboard:login'

    def get_queryset(self):
        queryset = Restaurant.objects.filter(
            owner=self.request.user.client, active=True)
        return queryset


class Detail(LoginRequiredMixin, TemplateView):
    model = Restaurant
    template_name = "Panel/restaurant_detail.html"
    login_url = 'Dashboard:login'

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class CreateDish(LoginRequiredMixin, CreateView):
    model = Dish
    form_class = DishForm
    template_name = "Panel/create_dish.html"
    success_url = reverse_lazy("Dashboard:list_restaurant")

    def get_form(self, *args, **kwargs):
        form = super(CreateDish, self).get_form(*args, **kwargs)
        form.fields['restaurant'].queryset = Restaurant.objects.filter(id=self.kwargs['restaurant'])
        return form

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})


class ListDish(LoginRequiredMixin, ListView):
    model = Dish
    template_name = "Panel/list_dish.html"
    form_class = DishForm

    def get_queryset(self):
        self.queryset = super(ListDish, self).get_queryset().filter(restaurant_id=self.kwargs['restaurant'])
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(ListDish, self).get_context_data(**kwargs)
        context['restaurant'] = self.kwargs['restaurant']
        return context


class UpdateDish(LoginRequiredMixin, UpdateView):
    model = Dish
    form_class = DishForm
    template_name = 'Panel/update_dish.html'
    success_url = reverse_lazy("Dashboard:list_restaurant")
    login_url = 'Dashboard:login'

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})

    def get_queryset(self):
        self.queryset = super(UpdateDish, self).get_queryset().filter(id=self.kwargs['pk'],
                                                                      restaurant__owner_id=self.request.user.client.id)
        get_object_or_404(self.queryset, id=self.kwargs['pk'], restaurant__owner_id=self.request.user.client.id)
        return self.queryset


class DeleteDish(LoginRequiredMixin, DeleteView):
    model = Dish
    template_name = 'Panel/delete_dish.html'
    success_url = reverse_lazy("Dashboard:list_restaurant")
    login_url = 'Dashboard:login'

    def get_queryset(self):
        dish = self.kwargs['pk']
        return self.model.objects.filter(id=dish)

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})


class CreateShedule(LoginRequiredMixin, CreateView):
    model = Shedule
    form_class = SheduleForm
    template_name = 'Panel/create_shedule.html'

    def get_form(self, *args, **kwargs):
        form = super(CreateShedule, self).get_form(*args, **kwargs)
        form.fields['restaurant'].queryset = Restaurant.objects.filter(id=self.kwargs['pk'], owner_id=self.request.user.client.id)
        return form

    def get_success_url(self):
        pk = self.object.restaurant_id
        return reverse_lazy("Dashboard:list_dish", kwargs={"restaurant": pk})


class ListShedule(LoginRequiredMixin, ListView):
    model = Shedule
    template_name = 'Panel/list_shedule.html'

    def get_queryset(self):
        self.queryset = Shedule.objects.filter(active=True, restaurant__id=self.kwargs['pk'], restaurant__owner_id=self.request.user.client.id)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(ListShedule, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class UpdateShedule(LoginRequiredMixin, UpdateView):
    model = Shedule
    template_name = 'Panel/update_shedule.html'
    form_class = SheduleForm

    def get_queryset(self):
        self.queryset = super(UpdateShedule, self).get_queryset().filter(active=True,
                                                                         restaurant__owner_id=self.request.user.client.id)
        get_object_or_404(self.queryset, id=self.kwargs['pk'], active=True,
                          restaurant__owner_id=self.request.user.client.id)
        return self.queryset

    def get_success_url(self):
        pk = self.kwargs['pk']

Dashboard/templates/Dashboard/index.html
{% extends 'Dashboard/base.html' %}
{% load static %}
{% block title %}Principal {% endblock title %}

{% block header %}

<div class="container">

  <div id="logo" class="pull-left">
    <a href="{% url 'Dashboard:home' %}">
      <img src="{% static 'Dashboard/img/icon.png' %}" alt="Flavors" srcset="">
    </a>
  </div>

  <nav id="nav-menu-container">
    <ul class="nav-menu">
      {% if not user.is_authenticated %}
      <li><a href="{% url 'Dashboard:login' %}">Entra</a></li>
      <li><a href="{% url 'Dashboard:new_user' %}">Registrate</a></li>
      {% else %}
      <li><a href="{% url 'Dashboard:update_profile' user.pk %}">{{ user.username }}</a></li>
      <li><a href="{% url 'Dashboard:panel' %}">Panel</a></li>
      <li><a href="{% url 'Dashboard:logout' %}">Logout</a></li>
      {% endif %}
    </ul>
  </nav><!-- #nav-menu-container -->
</div>
{% endblock header %}


{% block main %}
<section id="about">
  <div class="container">
    <div class="row about-container">

      <div class="col-lg-6 content order-lg-1 order-2">
        <h2 class="title">Sobre Nosotros.</h2>
        <p>
          Somos la primera plataforma enfocada a los sabores de los platillos. ¿Qué se te antoja hoy?
        </p>

        <div class="icon-box wow fadeInUp">
          <div class="icon"><i class="fa fa-cutlery"></i></div>
          <h4 class="title"><a href="">Imagina</a></h4>
          <p class="description">Todo inicia con tu antojo. ¿Algo dulce, salado, picante? Tu imaginación es el límite</p>
        </div>

        <div class="icon-box wow fadeInUp" data-wow-delay="0.2s">
          <div class="icon"><i class="fa fa-map"></i></div>
          <h4 class="title"><a href="">Busca</a></h4>
          <p class="description">A traves de una búsqueda personalizada encuentra exactamente el platillo que estás buscando.</p>
        </div>

        <div class="icon-box wow fadeInUp" data-wow-delay="0.4s">
          <div class="icon"><i class="fa fa-phone"></i></div>
          <h4 class="title"><a href="">Come</a></h4>
          <p class="description">No pierdas mas el tiempo y pide tu platillo a traves de cualquiera de la apps de comida con las que trabajamos.</p>
        </div>

      </div>

      <div class="col-lg-6 background order-lg-2 order-1 wow fadeInRight"></div>
    </div>

  </div>
</section><!-- #about -->


<!--==========================
     Information
    ============================-->
<section id="call-to-action">
  <div class="container wow fadeIn">
    <div class="row">
      <div class="col-lg-9 text-center text-lg-left">
        <h3 class="cta-title">Información</h3>
        <p class="cta-text"> Conoce nuestra forma de trabajar y como nos preocupamos por brindar el mejor servicio.</p>
      </div>
      <div class="col-lg-3 cta-btn-container text-center">
        <a class="cta-btn align-middle" href="#">Enterate</a>
      </div>
    </div>

  </div>
</section><!-- Information -->
<!--==========================
      Portfolio Section
    ============================-->
<section id="portfolio">
  <div class="container wow fadeInUp">
    <div class="section-header">
      <h3 class="section-title">Restaurantes</h3>
      <p class="section-description" style="color:black;">Nos enorgullece trabajar con los mejores restaurantes para llevar los mejores sabores hacia tí</p>
    </div>
    <div class="row">


    </div>
    <div class="row" id="portfolio-wrapper">
      <div class="col-lg-3 col-md-6 portfolio-item filter-app">
        <a href="">
          <img src="{% static 'Dashboard/img/portfolio/app1.jpg' %}" alt="">
          <div class="details">
            <h4>Savora Grill</h4>
            <span>Comida Italiana</span>
          </div>
        </a>
      </div>

      <div class="col-lg-3 col-md-6 portfolio-item filter-app">
        <a href="">
          <img src="{% static 'Dashboard/img/portfolio/app3.jpg' %}" alt="">
          <div class="details">
            <h4>Canjun Grill</h4>
            <span>Los mejores cortes de carne</span>
          </div>
        </a>
      </div>

      <div class="col-lg-3 col-md-6 portfolio-item filter-app">
        <a href="">
          <img src="{% static 'Dashboard/img/portfolio/app2.jpg' %}" alt="">
          <div class="details">
            <h4>Hamburguesas Toñito</h4>
            <span>Deliciosas hamburguesas</span>
          </div>
        </a>
      </div>

      <div class="col-lg-3 col-md-6 portfolio-item filter-card">
        <a href="">
          <img src="{% static 'Dashboard/img/portfolio/card1.jpg' %}" alt="">
          <div class="details">
            <h4>El taquito</h4>
            <span>Los mejores tacos</span>
          </div>
        </a>
      </div>
    </div>

  </div>
</section><!-- #portfolio -->

<!--==========================
     Plan Section
    ============================-->
<section id="team">
  <div class="container wow fadeInUp">
    <div class="section-header">
      <h3 class="section-title">Planes de Subscripción</h3>
      <p class="section-description" style="color:black;">¡Encuentra el Plan hecho a tu medida y subscríbete!</p>
    </div>
    <div class="row" >
      <div class="col-lg-3 col-md-6">
        <div class="member">
          <div class="pic"><img src="{% static 'Dashboard/img/simple.png' %}" alt=""></div>
          <h4>Plan Sencillo</h4>
          <span>Obtén acceso al panel de control, y desde allí administra tus platillos.</span>

        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="member">
          <div class="pic"><img src="{% static 'Dashboard/img/premium.png' %}" alt=""></div>
          <h4>Plan Premium</h4>
          <span>Obtén acceso al panel de control y ten acceso a privilegios exclusivos</span>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="member">
          <div class="pic"><img src="{% static 'Dashboard/img/all.png' %}" alt=""></div>
          <h4>Plan Ilimitado</h4>
          <span>Obtén acceso al panel de control y administra un número ilimitado de restaurantes y platillos.</span>
        </div>
      </div>
    </div>

  </div>
</section><!-- #team -->

<!--==========================
      Contact Section
    ============================-->

    <section id="contact">
      <div class="container wow fadeInUp">
        <div class="section-header">
          <h3 class="section-title">Contact Us</h3>
          <p class="section-description" style="color:black;">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </div>
      </div>

      <!-- Uncomment below if you wan to use dynamic maps -->
      <div class="container wow fadeInUp mt-5">
        <div class="row justify-content-center">

          <div class="col-lg-3 col-md-4">

            <div class="info">
              <div>
                <i class="fa fa-map-marker"></i>
                <p>A108 Adam Street<br>New York, NY 535022</p>
              </div>

              <div>
                <i class="fa fa-envelope"></i>
                <p>info@example.com</p>
              </div>

              <div>
                <i class="fa fa-phone"></i>
                <p>+1 5589 55488 55s</p>
              </div>
            </div>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-5 col-md-8">
            <div class="form">
              <div id="sendmessage">Your message has been sent. Thank you!</div>
              <div id="errormessage"></div>
              <form action="" method="post" role="form" class="contactForm">
                  {% csrf_token %}
                  {% for field in form %}
                      <div class="form-group">
                      {% if field.errors %}
                            <span style="color:red; margin-bottom: 5px">
                                {{field.errors}}
                            </span>
                      {% endif %}
                      {{ field }}
                      <div class="validation"></div>
                    </div>
                  {% endfor %}
                <div class="text-center"><button type="submit">Send Message</button></div>
              </form>
            </div>
          </div>

        </div>

      </div>
    </section>
{% endblock main %}

<!--==========================
    Footer
  ============================-->
{% block footer %}
<div class="footer-top">
  <div class="container">

  </div>
</div>

<div class="container">
  <div class="copyright">
    &copy; Copyright <strong>Flavors</strong>. All Rights Reserved
  </div>
  <div class="credits">
    <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Regna
        -->
  </div>
</div>
{% endblock footer %}

Dashboard/templates/Dashboard/login.html
{% extends 'Dashboard/base_registros.html' %}


{% block titulo %}
    Login
{% endblock titulo %}


{% block form %}
    <form class="login100-form validate-form" method="POST">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <p style="color:red; margin-bottom: 5px">
                Usuario o contraseña incorrectos, prueba de nuevo.
            </p>
        {% endif %}

        <div class="wrap-input100 validate-input m-b-26" data-validate="Ingrese un usuario">
            <span class="label-input100">{{ form.username.label}}</span>
            {{ form.username}}
            <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-18" data-validate="Ingrese una contraseña">
            <span class="label-input100">{{ form.password.label }}</span>
            {{ form.password }}
            <span class="focus-input100"></span>
        </div>

        <div class="flex-sb-m w-full p-b-30">
                ¿No tienes cuenta?
            <a href="{% url 'Dashboard:new_user' %}" class="txt1" style="color:rgb(204, 31, 31); font-weight: bold; font-size: 1.1rem;">
                Registrate
            </a>
        </div>
        <div class="flex-sb-m w-full p-b-30">
            <a href="{% url 'Dashboard:password_reset' %}" class="txt1" style="color:rgb(204, 31, 31); font-weight: bold; font-size: 1.1rem;">
                ¿Olvidaste tu contraseña?
            </a>
        </div>
        <button class="login100-form-btn" type="submit">
            Acceder
        </button>
    </form>
{% endblock form %}

Dashboard/templates/Dashboard/password_reset_confirm.html
{% extends 'Dashboard/base_registros.html' %}

{% block titulo %}
  Recupera tu Contraseña
{% endblock titulo %}

{% block form %}
    <div class="text-center" style="margin-top: 30px">
        <h1
            class="h4 text-gray-900 mb-4">
            Recupera tu Cuenta
        </h1>
    </div>

    {% if validlink %}
        <form class="user" method="POST">
            {% csrf_token %}
            <div class="form-group">
                    {% for field in form %}
                    {% if field.errors %}								
                        <span style="color:red; margin-bottom: 5px">
                            {{field.errors}}
                        </span>
                    {% endif %}

                    {{ field.label_tag }} {{ field }}
                {% endfor %}                                    
            <br>
            <hr>
            <br>
            <button class="btn btn-primary btn-user">
                Enviar Email
            </button>
        </form>
    {% else %}
    <p class="text-danger">Token Inválido</p>
    <p class="card-text">
      <a href="{% url 'Dashboard:password_reset' %}">Tramita un nuevo token</a>
    </p>
    {% endif %}
{% endblock form %}